###CREATE PERSON
POST http://localhost:8080/SKBLabIntern/api/v1/addIntern
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "email": "mesleroman@gmail.com",
  "isJavaBackEndDev": true,
  "skills": [
    "Java Core",
    "DI+IOC",
    "validation"
  ]
}